title: 'When In Manila'
content: 'When In Manila: Meet The Newest Al Fresco Bar of the Town'
image: image-299.jpg
date: '2023-07-28'
updated_by: 8e9abffb-d79b-46bd-9f70-6b8842586fbb
updated_at: 1700489424
blueprint: feature
