title: 'Filipino Pride'
content: '#FilipinoPride: This Filipino Restaurant Bagged Best Local Gem in Dubai Expo 2020!'
image: gallery/arcovia.jpg
date: '2023-07-28'
updated_by: 8e9abffb-d79b-46bd-9f70-6b8842586fbb
updated_at: 1702861235
blueprint: feature
duplicated_from: 'features::when-in-manila'
