title: q2
qoute_text: 'SCRIM Group is definitely doing something ipsum dolor sit amet, consectetur adipiscing elit. Curabitur auctor ultrices enim a tincidunt. Vivamus sed dui ultrices, consectetur ipsum ut, sollicitudin orci. Nunc eu metus ac ligula porttitor dapibus at id tellus.'
qoute_author: 'Second Author'
qoute_author_title: 'Second Author Title'
qoute_image: 791.png
updated_by: 8e9abffb-d79b-46bd-9f70-6b8842586fbb
updated_at: 1702771902
blueprint: qoute
